name: Call a reusable workflow

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'releases/**'
    tags:
      - 'v*'


jobs:
  call-workflow-16:
    uses: ./.github/workflows/docker-build.yml
    with:
      BASE_IMAGE: postgres:16.2
      MDTDB_VERSION: "18.4"
      PG_HINT_PLAN_VERSION: REL16_1_6_0
      PGAUDIT_VERSION: "16.0"
      VERSION_PREFIX: "16"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      NEXUS: ${{ secrets.NEXUS }}

  call-workflow-15:
    uses: ./.github/workflows/docker-build.yml
    with:
      BASE_IMAGE: postgres:15.6
      MDTDB_VERSION: "18.4"
      PG_HINT_PLAN_VERSION: REL15_1_5_1
      PGAUDIT_VERSION: "1.7.0"
      VERSION_PREFIX: "15"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      NEXUS: ${{ secrets.NEXUS }}

  call-workflow-14:
    uses: ./.github/workflows/docker-build.yml
    with:
      BASE_IMAGE: postgres:14.11
      MDTDB_VERSION: "18.4"
      PG_HINT_PLAN_VERSION: REL14_1_4_2
      PGAUDIT_VERSION: "1.6.2"
      VERSION_PREFIX: "14"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      NEXUS: ${{ secrets.NEXUS }}

  call-workflow-13:
    uses: ./.github/workflows/docker-build.yml
    with:
      BASE_IMAGE: postgres:13.14
      MDTDB_VERSION: "18.4"
      PG_HINT_PLAN_VERSION: REL13_1_3_9
      PGAUDIT_VERSION: "1.5.2"
      VERSION_PREFIX: "13"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      NEXUS: ${{ secrets.NEXUS }}